[book]
authors = ["Seb Blair"]
title = "QinetiQ Material - University of Greenwich"
language = "en"
multilingual = false
src = "content"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/TeachingMaterial/QinetiQMaterial"
edit-url-template = "https://github.com/TeachingMaterial/QinetiQMaterial/edit/master/{path}"
input-404 = "404/404.md"

[output.html.print]
enable = false

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
